### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by damianatorrpm** [danielknobe/blobbyvolley2#1] opened 2019-12-28 18:50 UTC
This is a friendly request if you want to /and/or/ create/(co-)maintain your application

Best Regards
Damian

**Comment by danielknobe** [comment] 2019-12-29 10:48
Hello,
thank you for the request. This is planned for the 1.1 alpha release, now.
About contribution I would be pleased.

**Comment by TomaszGasior** [comment] 2020-10-19 20:32
@danielknobe 

I prepared flatpak version of blobby volley: https://github.com/TomaszGasior/blobby-flatpak I would like to ask you to test what I did. You may test these commands in your distro if you work on Linux or run them from, for example, Fedora 32 live image:

```
git clone https://github.com/TomaszGasior/blobby-flatpak.git
cd blobby-flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install org.freedesktop.Sdk//20.08
flatpak install org.freedesktop.Platform//20.08
flatpak-builder build-dir de.blobbyvolley.BlobbyVolley2.yaml --force-clean --install --user
```

If you take a look at my work, then I will try to submit the package to Flathub, official flatpak repository, to make it available in all Linux distros. Package is based on commit matching last stable release.

The following command  runs server from inside of flatpak container aka sandbox. I am not sure whether we want to support running server from this. The whole file system is ready only and I am not sure whether blobby-server binary supports using config file from ~/.blobby.

```
flatpak run --command=blobby-server de.blobbyvolley.BlobbyVolley2 -n
```

Configurations files from ~/.blobby are saved in ~/.var/app/de.blobbyvolley.BlobbyVolley2/.blobby. Also, the code has applied some patches to make it working with `/app` paths, which are specific to flatpak packaged apps.

**Comment by damianatorrpm** [comment] 2020-10-20 10:52
@TomaszGasior I tested it works fine for me.
I don't know about server details but the tmp/cache/config (XDG_HOME/XDG_CONFIG) dirs are writable.
Additionally when submitted to flathub they will review the yaml as well.
Although I see --socket=pulseaudio in the yaml
after building it hangs
```
[tux@localhost blobby-flatpak]$ flatpak run --command=blobby de.blobbyvolley.BlobbyVolley2 
Warning: Can't create device with desired audio spec!
Reason: Audio subsystem is not initialized
Warning: Couldn't open audio Device!
Reason: Audio subsystem is not initialized
```

**Comment by TomaszGasior** [comment] 2020-10-20 11:40
Unfortunately I am not able to reproduce your issue with sound. Works for me on Fedora 32 (both my current installation and live ISO).

**Comment by damianatorrpm** [comment] 2020-10-20 11:41
Yes weird I tried it from the build dir, after installing the flatpak it works fine and with sound

**Comment by danielknobe** [comment] 2020-10-20 18:56
@TomaszGasior Your work looks great.
@damianatorrpm Thanks for testing.

Tested with Mint 19.3 x86 64bit and works without any issue. I would be pleased if you submit the package to Flathub. Then more people will enjoy blobby volley 1.0 ;).
This issue should be closed if this step is done.

This is also a cool solution to test upcoming releases in the future.

**Comment by TomaszGasior** [comment] 2020-10-25 18:02
Blobby Volley 2 is waiting for moderation :+1: https://github.com/flathub/flathub/pull/1899

**Comment by TomaszGasior** [comment] 2020-10-25 18:05
@danielknobe It will be nice if some time you will try to address issues fixed by downstream patches included in Flatpak package. As you can see in discussion, Flathub maintainers don't like downstream patches and it seems to be reasonable.

**Comment by TomaszGasior** [comment] 2020-10-26 22:12
Blobby Volley 2 is available in Flathub! https://flathub.org/apps/details/de.blobbyvolley.BlobbyVolley2 This issue can be closed now.

**Comment by danielknobe** [comment] 2020-11-01 15:28
Nice job. Looks great. Now more people can enjoy blobby volley 2.
The other issues can be fixed as soon as I have some time.
It is a good idea to implement some freedesktop specifications.

**Closed by danielknobe** 2020-11-01 15:28 UTC
Labels: enhancement
